[build]
  command = "npm run build"  # Ensure this matches your build command
  publish = "build"          # The directory where your built files are output (default is 'build' for React)

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200